# Generated by Django 3.2 on 2022-10-25 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Papers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='', unique=True)),
                ('abstract', models.TextField(default='')),
                ('link', models.URLField(default='')),
                ('image', models.BinaryField(default=b'')),
                ('authors', models.TextField(default='')),
                ('tfidfsummary', models.TextField(default='')),
                ('category', models.CharField(default='', max_length=200)),
                ('date', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
